// ============================================================
//  generators/markdown.ts
//  100% LOCAL markdown generator — zero external URLs
// ============================================================
import type { AppState, SectionId, PinnedProject } from '../types'
import { t } from '../data/i18n'
import { generateTypingSVG, generateWaveSVG, generateBadgeSVG, generateVisitorBadgeSVG } from './typing-svg'
import { generateGithubStatsCard, generateGithubStreakCard, generateTopLangsCard } from './github-stats'
import { generateSnakeReadmeSection } from './snake-game'
import { generateServiceCard, SERVICE_CARD_IDS } from './service-cards'
import { getFontById } from '../data/fonts'

// Base URL for assets when the README is hosted in the user's own repo
// User should set this to their repo's raw URL after downloading
const ASSET_NOTE = `<!-- 
  ⚠️  IMPORTANTE: este README foi gerado 100% localmente.
  Os ícones e SVGs estão em ./assets/ neste repositório.
  Copie a pasta assets/ para o seu repositório username/username.
  Nenhum serviço externo é necessário.
-->`

export function generateMarkdown(state: AppState): string {
  const { lang, profile, typing, icons, social, plugins, about, projects, sectionOrder, statsTheme } = state
  const tr = (key: string) => t(lang, key)
  const user = profile.username || 'seu-username'

  // Typing SVG: always embed as data URI in offline-first mode
  const typingConfig = typing
  const font = getFontById(typing.font)
  const lines = typing.texts.filter(s => s.trim())

  let typingMd = ''
  if (lines.length) {
    // Embed the SVG as a data URI so it works without any hosting
    const svg = generateTypingSVG({ ...typingConfig, texts: lines })
    const encoded = svgToDataURI(svg)
    typingMd = `<img src="${encoded}" alt="Typing SVG" />`
  }

  // Icons markdown: inline SVG data URIs (fully offline)
  const iconsMd = buildIconsMarkdown(state)

  // Social badges: inline SVG data URIs
  const socialMd = buildSocialBadges(state)

  // Build ordered sections
  const sections: string[] = []

  sections.push(ASSET_NOTE)
  sections.push('')

  for (const sec of sectionOrder) {
    if (!sec.enabled) continue
    const chunk = buildSection(sec.id, state, { tr, user, typingMd, iconsMd, socialMd, font })
    if (chunk) sections.push(chunk)
  }

  // Footer
  sections.push(`---\n\n<div align="center">\n  <sub>⚡ ${lang === 'pt' ? 'Gerado com' : 'Generated with'} <a href="https://github.com/Davibzf/Readme-Builder">README Builder</a> — 100% local, sem dependências externas.</sub>\n</div>`)

  return sections.join('\n\n')
}

// ── SECTION BUILDERS ─────────────────────────────────────────

function buildSection(
  id: SectionId,
  state: AppState,
  ctx: { tr: (k:string)=>string; user: string; typingMd: string; iconsMd: string; socialMd: string; font: ReturnType<typeof getFontById> }
): string {
  const { tr, user, typingMd, iconsMd, socialMd } = ctx
  const { profile, plugins, about, projects, lang, statsTheme } = state

  switch(id) {
    case 'header': {
      const waveFields = plugins.wave?.fields ?? {}
      const waveColor = normalizeHex(waveFields.color || '58a6ff')
      const waveHeaderText = waveFields.headerText?.trim() ?? ''
      const waveSvg = plugins['wave']?.enabled
        ? svgToImgTag(generateWaveSVG('header', waveColor, 120, waveHeaderText), 'Wave header')
        : ''

      let md = `<div align="center">\n\n`
      if (waveSvg) md += waveSvg + '\n\n'
      md += `# ${profile.displayName}\n`
      md += `### ${getFocusLabel(profile.focus, lang)}\n\n`
      if (profile.bio) md += `> *${profile.bio}*\n\n`
      if (profile.location) md += `📍 ${profile.location}\n\n`
      if (profile.openToWork) {
        const badge = generateBadgeSVG({ label: 'Open to work', message: '✓', labelColor: '238636', messageColor: '2ea043', style: 'flat-square' })
        md += `<img src="${svgToDataURI(badge)}" alt="Open to work">\n\n`
      }
      if (typingMd) md += typingMd + '\n\n'
      if (socialMd) md += socialMd + '\n\n'
      md += `</div>`
      return md
    }

    case 'about': {
      if (!about.enabled) return ''
      let md = `## ${tr('rm_about')}\n\n`
      for (const p of about.paragraphs) {
        if (p.trim()) md += p.trim() + '\n\n'
      }
      const facts = about.facts.filter(f => f.text.trim())
      if (facts.length) {
        md += facts.map(f => `- ${f.emoji} ${f.text}`).join('\n')
        md += '\n'
      }
      return md
    }

    case 'icons': {
      if (!iconsMd) return ''
      return `## ${tr('rm_stack')}\n\n${iconsMd}`
    }

    case 'stats': {
      const hasStats = ['stats','streak','langs'].some(p => plugins[p as keyof typeof plugins]?.enabled)
      if (!hasStats) return ''

      let md = `## ${tr('rm_stats')}\n\n`
      md += `<!-- GitHub Stats cards generated by README Builder. No external card service required. -->\n`
      md += `<div align="center">\n\n`
      if (plugins['stats']?.enabled)
        md += `<img src="${svgToDataURI(generateGithubStatsCard(state))}" alt="GitHub Stats" />\n`
      if (plugins['streak']?.enabled)
        md += `<img src="${svgToDataURI(generateGithubStreakCard(state))}" alt="GitHub Streak" />\n`
      if (plugins['langs']?.enabled)
        md += `<img src="${svgToDataURI(generateTopLangsCard(state))}" alt="Top Languages" />\n`
      md += `\n</div>`
      return md
    }

    case 'projects': {
      const active = projects.filter(p => p.enabled)
      if (!active.length) return ''
      let md = `## ${tr('rm_projects')}\n\n`
      md += `<div align="center">\n\n`
      // Local project cards using inline SVG badges
      for (const proj of active) {
        md += buildProjectCard(proj)
      }
      md += `\n</div>`
      return md
    }

    case 'snake': {
      if (!plugins['snake']?.enabled) return ''
      return generateSnakeReadmeSection(user, lang)
    }

    case 'plugins': {
      return buildPluginsSection(state, tr, user)
    }

    case 'footer': {
      const waveFields = plugins.wave?.fields ?? {}
      const waveColor = normalizeHex(waveFields.color || '58a6ff')
      const waveFooterText = waveFields.footerText?.trim() ?? ''
      const waveSvg = plugins['wave']?.enabled
        ? '\n\n' + svgToImgTag(generateWaveSVG('footer', waveColor, 80, waveFooterText), 'Wave footer')
        : ''
      return `<div align="center">\n  <a href="https://github.com/${user}">github.com/${user}</a>${waveSvg}\n</div>`
    }

    default: return ''
  }
}

// ── PLUGINS SECTION ───────────────────────────────────────────
function buildPluginsSection(state: AppState, tr: (k:string)=>string, user: string): string {
  const { plugins, statsTheme, lang } = state
  const chunks: string[] = []

  if (plugins['trophy']?.enabled) {
    chunks.push(`## 🏆 ${tr('rm_trophies')}\n\n<div align="center">\n\n<!-- requires internet -->\n![Trophies](https://github-profile-trophy.vercel.app/?username=${user}&theme=${statsTheme}&no-frame=true&row=1&column=7)\n\n</div>`)
  }
  if (plugins['activitygraph']?.enabled) {
    chunks.push(`## 📈 ${tr('rm_activity')}\n\n<div align="center">\n\n<!-- requires internet -->\n[![Activity Graph](https://github-readme-activity-graph.vercel.app/graph?username=${user}&theme=react-dark&hide_border=true)](https://github.com/${user})\n\n</div>`)
  }
  for (const id of SERVICE_CARD_IDS) {
    if (!plugins[id]?.enabled) continue
    const heading = getServiceHeading(id, tr)
    chunks.push(`## ${heading}\n\n<div align="center">\n\n<img src="${svgToDataURI(generateServiceCard(state, id))}" alt="${heading}" />\n\n</div>`)
  }
  if (false && plugins['wakatime']?.enabled) {
    const wu = plugins['wakatime'].fields['wakaUsername'] || user
    chunks.push(`## ⏱ ${tr('rm_wakatime')}\n\n<div align="center">\n\n<!-- requires WakaTime account + internet -->\n![WakaTime](https://github-readme-stats.vercel.app/api/wakatime?username=${wu}&theme=${statsTheme}&hide_border=true)\n\n</div>`)
  }
  if (false && plugins['leetcode']?.enabled) {
    const lu = plugins['leetcode'].fields['leetcodeUser'] || user
    chunks.push(`## 🧩 ${tr('rm_leetcode')}\n\n<div align="center">\n\n<!-- requires internet -->\n[![LeetCode](https://leetcard.jacoblin.cool/${lu}?theme=dark)](https://leetcode.com/${lu})\n\n</div>`)
  }
  if (false && plugins['codewars']?.enabled) {
    const cu = plugins['codewars'].fields['codewarsUser'] || user
    chunks.push(`## ⚔️ ${tr('rm_codewars')}\n\n<div align="center">\n\n[![Codewars](https://www.codewars.com/users/${cu}/badges/large)](https://www.codewars.com/users/${cu})\n\n</div>`)
  }
  if (false && plugins['wakatime']?.enabled) {
    const wu = plugins['wakatime'].fields['wakaUsername'] || user
    chunks.push(`## ⏱ ${tr('rm_wakatime')}\n\n<div align="center">\n\n<!-- requires WakaTime account + internet -->\n![WakaTime](https://github-readme-stats.vercel.app/api/wakatime?username=${wu}&theme=${statsTheme}&hide_border=true)\n\n</div>`)
  }
  if (false && plugins['leetcode']?.enabled) {
    const lu = plugins['leetcode'].fields['leetcodeUser'] || user
    chunks.push(`## 🧩 ${tr('rm_leetcode')}\n\n<div align="center">\n\n<!-- requires internet -->\n[![LeetCode](https://leetcard.jacoblin.cool/${lu}?theme=dark)](https://leetcode.com/${lu})\n\n</div>`)
  }
  if (false && plugins['codewars']?.enabled) {
    const cu = plugins['codewars'].fields['codewarsUser'] || user
    chunks.push(`## ⚔️ ${tr('rm_codewars')}\n\n<div align="center">\n\n[![Codewars](https://www.codewars.com/users/${cu}/badges/large)](https://www.codewars.com/users/${cu})\n\n</div>`)
  }
  if (false && plugins['wakatime']?.enabled) {
    const wu = plugins['wakatime'].fields['wakaUsername'] || user
    chunks.push(`## ⏱ ${tr('rm_wakatime')}\n\n<div align="center">\n\n<!-- requires WakaTime account + internet -->\n![WakaTime](https://github-readme-stats.vercel.app/api/wakatime?username=${wu}&theme=${statsTheme}&hide_border=true)\n\n</div>`)
  }
  if (false && plugins['leetcode']?.enabled) {
    const lu = plugins['leetcode'].fields['leetcodeUser'] || user
    chunks.push(`## 🧩 ${tr('rm_leetcode')}\n\n<div align="center">\n\n<!-- requires internet -->\n[![LeetCode](https://leetcard.jacoblin.cool/${lu}?theme=dark)](https://leetcode.com/${lu})\n\n</div>`)
  }
  if (false && plugins['codewars']?.enabled) {
    const cu = plugins['codewars'].fields['codewarsUser'] || user
    chunks.push(`## ⚔️ ${tr('rm_codewars')}\n\n<div align="center">\n\n[![Codewars](https://www.codewars.com/users/${cu}/badges/large)](https://www.codewars.com/users/${cu})\n\n</div>`)
  }
  if (plugins['views']?.enabled) {
    const label = lang === 'pt' ? 'VISITANTES' : 'VISITORS'
    chunks.push(`<div align="center">\n\n<img src="${svgToDataURI(generateVisitorBadgeSVG(label))}" alt="${label}" />\n\n</div>`)
  }

  return chunks.join('\n\n')
}

// ── ICONS MARKDOWN ────────────────────────────────────────────
function buildIconsMarkdown(state: AppState): string {
  const { icons } = state
  if (!icons.selected.length) return ''

  // Use only local assets and force row breaks so "icons per row" is respected.
  const perRow = getSafePerRow(icons.perRow)
  const align = icons.align === 'left' ? 'left' : 'center'
  const rows: string[][] = []
  for (let i = 0; i < icons.selected.length; i += perRow) {
    rows.push(icons.selected.slice(i, i + perRow))
  }

  const rowsMd = rows.map(row =>
    row.map(id =>
      `<img src="./assets/icons/${id}.svg" width="40" alt="${id}" title="${id}" />`
    ).join(' ')
  ).join('\n<br />\n')

  return `<div align="${align}">\n\n${rowsMd}\n\n</div>`
}

function getSafePerRow(value: number): number {
  return Number.isFinite(value) ? Math.min(20, Math.max(1, value)) : 12
}

// ── SOCIAL BADGES ─────────────────────────────────────────────
function normalizeHex(value: string): string {
  const hex = value.replace('#', '').trim()
  return /^[0-9a-fA-F]{6}$/.test(hex) ? hex : '58a6ff'
}

function buildSocialBadges(state: AppState): string {
  const { social } = state
  const badges: string[] = []

  const SOCIAL_DEFS: Array<{ key: keyof typeof social; label: string; labelColor: string; msgColor: string; icon: string }> = [
    { key: 'linkedin',  label: 'LinkedIn',  labelColor: '0077B5', msgColor: '0077B5', icon: 'linkedin' },
    { key: 'twitter',   label: 'Twitter',   labelColor: '1DA1F2', msgColor: '1DA1F2', icon: 'twitter' },
    { key: 'website',   label: 'Portfolio', labelColor: 'FF5722', msgColor: 'FF5722', icon: 'website' },
    { key: 'email',     label: 'Email',     labelColor: 'D14836', msgColor: 'D14836', icon: 'email' },
    { key: 'discord',   label: 'Discord',   labelColor: '5865F2', msgColor: '5865F2', icon: 'discord' },
    { key: 'youtube',   label: 'YouTube',   labelColor: 'FF0000', msgColor: 'FF0000', icon: 'youtube' },
    { key: 'devto',     label: 'Dev.to',    labelColor: '0A0A0A', msgColor: '0A0A0A', icon: 'devto' },
  ]

  for (const def of SOCIAL_DEFS) {
    const val = social[def.key]
    if (!val) continue
    const svg = generateBadgeSVG({
      label: def.label, message: '',
      labelColor: def.labelColor, messageColor: def.msgColor,
      style: 'for-the-badge',
    })
    // Just use local badge + link
    const url = getSocialUrl(def.key, val)
    badges.push(`<a href="${url}"><img src="${svgToDataURI(svg)}" alt="${def.label}"></a>`)
  }

  return badges.length ? badges.join('\n') : ''
}

function getSocialUrl(key: string, val: string): string {
  switch(key) {
    case 'linkedin': return `https://linkedin.com/in/${val}`
    case 'twitter':  return `https://twitter.com/${val.replace('@','')}`
    case 'website':  return val.startsWith('http') ? val : 'https://' + val
    case 'email':    return `mailto:${val}`
    case 'discord':  return `https://discord.gg/${val}`
    case 'youtube':  return `https://youtube.com/@${val}`
    case 'devto':    return `https://dev.to/${val}`
    default: return '#'
  }
}

// ── PROJECT CARDS ─────────────────────────────────────────────
function buildProjectCard(proj: PinnedProject): string {
  const stars = proj.stars ? `⭐ ${proj.stars}  ` : ''
  const forks = proj.forks ? `🍴 ${proj.forks}  ` : ''
  const lang  = proj.language ? `\`${proj.language}\`` : ''
  const link  = proj.url ? `[${proj.name}](${proj.url})` : proj.name
  return `**${link}** — ${proj.description}\n${lang} ${stars}${forks}\n\n`
}

// ── UTILS ─────────────────────────────────────────────────────
function svgToDataURI(svg: string): string {
  const encoded = encodeURIComponent(svg)
  return `data:image/svg+xml,${encoded}`
}

function svgToImgTag(svg: string, alt: string): string {
  return `<img src="${svgToDataURI(svg)}" alt="${alt}" width="100%">`
}

function getFocusLabel(focus: string, lang: string): string {
  const map: Record<string, {pt:string;en:string}> = {
    fullstack: {pt:'Full Stack Developer',   en:'Full Stack Developer'},
    backend:   {pt:'Backend Developer',      en:'Backend Developer'},
    frontend:  {pt:'Frontend Developer',     en:'Frontend Developer'},
    mobile:    {pt:'Mobile Developer',       en:'Mobile Developer'},
    devops:    {pt:'DevOps / SRE Engineer',  en:'DevOps / SRE Engineer'},
    data:      {pt:'Data Engineer / AI',     en:'Data Engineer / AI'},
    security:  {pt:'Security Engineer',      en:'Security Engineer'},
    gamedev:   {pt:'Game Developer',         en:'Game Developer'},
    student:   {pt:'Estudante de Dev',       en:'Dev Student'},
  }
  const entry = map[focus]
  if (!entry) return focus
  return lang === 'en' ? entry.en : entry.pt
}

// ── EXPORT ────────────────────────────────────────────────────
export function downloadMarkdown(content: string, filename = 'README.md'): void {
  const blob = new Blob([content], { type: 'text/markdown' })
  const url  = URL.createObjectURL(blob)
  const a    = document.createElement('a')
  a.href = url; a.download = filename; a.click()
  URL.revokeObjectURL(url)
}
